# Generated by Django 2.2.3 on 2019-08-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectNLMK',
            fields=[
                ('objectnlmk', models.CharField(blank=True, max_length=250, primary_key=True, serialize=False, verbose_name='Объект')),
                ('bgp_as', models.CharField(max_length=10, verbose_name='AS')),
                ('enterprise', models.CharField(blank=True, max_length=250, verbose_name='Предприятие')),
                ('enterprise_addr', models.CharField(blank=True, max_length=250, verbose_name='Адрес предприятия')),
            ],
            options={
                'verbose_name': 'Объект группы компаний',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код оператора')),
                ('operator_name', models.CharField(blank=True, max_length=250, verbose_name='Название оператора')),
            ],
            options={
                'verbose_name': 'Оператор',
            },
        ),
        migrations.CreateModel(
            name='Voipgw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voip_ip', models.CharField(max_length=10, verbose_name='Ip voip gw')),
                ('voip_gw', models.CharField(blank=True, max_length=250, verbose_name='Имя voip gw')),
                ('objectnlmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.ObjectNLMK', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Voip gw',
            },
        ),
        migrations.CreateModel(
            name='Voipprefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, verbose_name='Префикс')),
                ('width', models.CharField(blank=True, max_length=250, verbose_name='Длина префикса')),
                ('voip_gw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.Voipgw', verbose_name='Имя voip gw')),
            ],
            options={
                'verbose_name': 'Voip префикс',
            },
        ),
        migrations.CreateModel(
            name='Type_channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_channel', models.CharField(blank=True, max_length=50, verbose_name='Тип канала')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.Operator', verbose_name='Код оператора')),
            ],
            options={
                'verbose_name': 'Тип канала',
            },
        ),
        migrations.CreateModel(
            name='Peering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.CharField(blank=True, max_length=50, verbose_name='Свитч')),
                ('port', models.CharField(blank=True, max_length=50, verbose_name='Порт свитча')),
                ('bandwidth', models.CharField(blank=True, max_length=50, verbose_name='Ширина пиринга')),
                ('contract', models.CharField(blank=True, max_length=250, verbose_name='Договор/Заказ')),
                ('address_peering', models.CharField(max_length=150, verbose_name='Адрес пиринга')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.Operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'AS',
            },
        ),
        migrations.CreateModel(
            name='Optelephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=250, verbose_name='Телефон оператора')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.Operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Телефон оператора',
            },
        ),
        migrations.CreateModel(
            name='Opemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email оператора')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.Operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Email',
            },
        ),
        migrations.CreateModel(
            name='L3net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, max_length=250, verbose_name='Пиринговая сеть')),
                ('op_ip', models.CharField(blank=True, max_length=250, verbose_name='IP оператора')),
                ('our_ip', models.CharField(blank=True, max_length=250, verbose_name='IP со стороны PSI')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.Operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Сети стыков по L3',
            },
        ),
        migrations.CreateModel(
            name='Clientcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=10, verbose_name='ФИО')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=250, verbose_name='Телефон')),
                ('objectnlmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.ObjectNLMK', verbose_name='object')),
            ],
            options={
                'verbose_name': 'Clients contacts',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ip')),
                ('router', models.CharField(max_length=50, verbose_name='Имя роутера')),
                ('interface', models.CharField(max_length=50, verbose_name='Интерфейс/влан')),
                ('pe', models.CharField(max_length=50, verbose_name='PE роутер')),
                ('type_ch', models.CharField(max_length=50, verbose_name='Тип канала')),
                ('bandwidth', models.CharField(max_length=50, verbose_name='Ширина канала')),
                ('address_channel', models.CharField(max_length=250, verbose_name='Адрес точки принятия канала')),
                ('notes', models.CharField(max_length=250, verbose_name='Примечания')),
                ('bgp_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.ObjectNLMK', verbose_name='AS')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlmkapp.Operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Канал',
            },
        ),
    ]
