# Generated by Django 2.2.3 on 2019-08-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectnlmk',
            options={'verbose_name': 'Объект группы компаний', 'verbose_name_plural': 'Объекты группы компаний'},
        ),
    ]
