# Generated by Django 2.2.3 on 2019-08-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0002_auto_20190814_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы'},
        ),
    ]
