# Generated by Django 2.2.3 on 2019-08-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0003_auto_20190814_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peering',
            options={'verbose_name': 'Peering'},
        ),
    ]
