# Generated by Django 2.2.3 on 2019-08-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0004_auto_20190815_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
    ]
