# Generated by Django 2.2.3 on 2019-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0005_auto_20190816_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peering',
            name='address_peering',
            field=models.CharField(max_length=250, verbose_name='Адрес пиринга'),
        ),
    ]
