# Generated by Django 2.2.3 on 2019-08-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0006_auto_20190816_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'Client contact', 'verbose_name_plural': 'Clients contacts'},
        ),
        migrations.AlterModelOptions(
            name='l3net',
            options={'verbose_name': 'Сети стыков по L3', 'verbose_name_plural': 'Сети стыков по L3'},
        ),
        migrations.AlterModelOptions(
            name='optelephone',
            options={'verbose_name': 'Телефон оператора', 'verbose_name_plural': 'Телефоны операторов'},
        ),
        migrations.AlterModelOptions(
            name='peering',
            options={'verbose_name': 'Peering', 'verbose_name_plural': 'Peerings'},
        ),
        migrations.AlterModelOptions(
            name='type_channel',
            options={'verbose_name': 'Тип канала', 'verbose_name_plural': 'Типы каналов'},
        ),
        migrations.AlterModelOptions(
            name='voipprefix',
            options={'verbose_name': 'Voip префикс', 'verbose_name_plural': 'Voip префиксы'},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='type_ch',
        ),
    ]
