# Generated by Django 2.2.3 on 2019-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0007_auto_20190816_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='fio',
            field=models.CharField(max_length=59, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='voipgw',
            name='voip_ip',
            field=models.CharField(max_length=16, verbose_name='Ip voip gw'),
        ),
    ]
