# Generated by Django 2.2.3 on 2019-08-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0009_auto_20190816_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voipprefix',
            old_name='voip_gw',
            new_name='voipgw',
        ),
    ]
