# Generated by Django 2.2.3 on 2019-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0010_auto_20190819_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l3net',
            name='op_ip',
            field=models.GenericIPAddressField(verbose_name='IP оператора'),
        ),
    ]
