# Generated by Django 2.2.3 on 2019-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0011_auto_20190819_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'Контакты на местах', 'verbose_name_plural': 'Контакты на местах'},
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
