# Generated by Django 2.2.3 on 2019-08-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlmkapp', '0012_auto_20190820_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opemail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email оператора'),
        ),
    ]
